emit:
  - "@typespec/openapi3"
options:
  "@typespec/openapi3":
    file-type: json
    output-file: api-i18n-resources-x.y.z.json
    emitter-output-dir: "{project-root}/../../doc/api-i18n-resources"
